name: Deploy Kambo Website to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Build application
      run: |
        cd client
        npm ci
        npm run build
        cd ..
        npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
        mkdir -p dist/public
        cp -r client/dist/* dist/public/

    - name: Create minimal package.json for production
      run: |
        echo '{
          "name": "kambo-website",
          "version": "1.0.0",
          "main": "index.js",
          "scripts": {
            "start": "node index.js"
          },
          "engines": {
            "node": ">=20.0.0"
          }
        }' > dist/package.json

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C1B3790B2E6146F1941B5972BCA6A677 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A471FA0998DC48B791E71FB63E8563C0 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_77F65BB000F44420B1D2C4FD6BC11222 }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-kamboHealing'
        slot-name: 'Production'
        package: './dist'