# Build and deploy Kambo website to Azure App Service
name: Azure Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci --production

    - name: Build client
      run: |
        cd client
        npm ci
        npm run build
        cd ..
        mkdir -p dist/public
        cp -r client/dist/* dist/public/

    - name: Build server
      run: npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C1B3790B2E6146F1941B5972BCA6A677 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A471FA0998DC48B791E71FB63E8563C0 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_77F65BB000F44420B1D2C4FD6BC11222 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-kamboHealing'
        slot-name: 'Production'
        package: .