name: Build and deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci --omit=dev

    - name: Build client application
      run: |
        cd client
        # Generate package-lock.json if it doesn't exist
        if [ ! -f "package-lock.json" ]; then
          echo "Generating package-lock.json..."
          npm install --package-lock-only
        fi
        npm ci
        npm run build
        cd ..

    - name: Build server application
      run: |
        # Create dist directory and build server
        npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --minify
        
        # Copy client build to expected locations
        mkdir -p dist/public
        cp -r client/dist/* dist/public/
        
        # Also copy to root public for server compatibility
        mkdir -p public
        cp -r client/dist/* public/

    - name: Verify build outputs
      run: |
        echo "Build verification:"
        echo "- Server bundle: $(ls -la dist/index.js 2>/dev/null || echo 'MISSING')"
        echo "- Client files: $(ls -la dist/public/index.html 2>/dev/null || echo 'MISSING')"
        echo "- Public files: $(ls -la public/index.html 2>/dev/null || echo 'MISSING')"

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-kambohealing'
        slot-name: 'Production'
        package: .
        startup-command: 'node dist/index.js'